apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: {{ .Values.replicaCount }}
  selector: { matchLabels: { app: consumer } }
  template:
    metadata: { labels: { app: consumer } }
    spec:
      containers:
      - name: consumer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env: []
