apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: {{ .Values.replicaCount }}
  selector: { matchLabels: { app: producer } }
  template:
    metadata: { labels: { app: producer } }
    spec:
      containers:
      - name: producer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env: []
